Doist/reactist

examples/modal-box/src/index.js
webpack.config.js

no need to accept this pull request. just to show how we could make it work with webpack libraries.

webpack exports a library

---

README.md

Added npm version, mit licence and PRs welcome badges to README

---

package-lock.json

**Short description:**
These changes were auto-generated when I ran `npm install`. I'm not sure if they're needed but I'd assume so, otherwise other people will get them as well. So I'm submitting this PR just in case. Or else let me know what to do about these changes?
**PR Checklist:**

Add changes generated by npm install in package-lock.json

---

.prettierignore
.storybook/stories/components/CheckboxStory.js
.storybook/stories/components/InputStory.js
.storybook/stories/components/LoadingStory.js
.storybook/stories/components/ModalStory.js
.storybook/stories/components/styles/button_story.less
.storybook/stories/components/styles/loading_story.less
.storybook/stories/components/styles/tooltip_story.less
package-lock.json
package.json
src/components/styles/avatar.less
src/components/styles/button.less
src/components/styles/checkbox.less
src/components/styles/color_picker.less
src/components/styles/constants.less
src/components/styles/dropdown.less
src/components/styles/error_message.less
src/components/styles/modal.less
src/components/styles/popover.less
src/components/styles/range_input.less
src/components/styles/tabs.less
src/components/styles/time.less
src/components/styles/tip.less

Sets up some automated git hooks to keep the codebase healthy:
* Applies prettier formatting to all the changes upon commit
* Runs `eslint` upon commit, and auto-fixes issues if possible, or fails the commit with errors
* Runs the tests before every push, and fails the push if tests fail
Fixes #134, and supersedes #135.

Automated git hooks

---

README.md

As discussed in our 1on1 here's a small doc on how to publish a new version of reactist 👍

Documents release / publish workflow in readme

---

.github/workflows/publish.yml
.github/workflows/pull_request.yml
.npmrc
CHANGELOG.md
package-lock.json
package.json

This adds a GitHub action to run tests, type checks, linters and build on PR's, and authenticates for pulling packages off of the GitHub package repository.
-   [x] Executed `npm run lint` and made sure no errors / warnings were shown
-   [x] Executed `npm run test` and made sure all tests are passing
-   [x] Bumped version in `package.json`
-   [x] Updated all static build artifacts (`npm run build-all`)

Add action for pull requests

---

.github/PULL_REQUEST_TEMPLATE.md
.huskyrc.json
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
package.json

Closes https://twitter.com/tanvirraj/status/1283801644770050048 😄
What the title says. Also some minor adjustments to the README and PR template in light of the improved npm scripts.
No release required.

Add a CONTRIBUTING and CODE_OF_CONDUCT documents, improved npm scripts

---

.github/workflows/coverage-reporting.yml
package.json

Reports our test coverage to coveralls so we can check how it evolves over time.

Adds coverage reporting with coveralls

---

README.md

After going through the release process recently, I thought the Release section could include further details. I've included some of the details found within the PR checklist.
Does not require a new version being published (`README.md` has been updated)

docs: Update readme with further details on the release process

---

src/new-components/box/box.module.css
src/new-components/checkbox-field/checkbox-field.module.css
src/new-components/checkbox-field/checkbox-field.stories.tsx
src/new-components/checkbox-field/checkbox-field.test.tsx
src/new-components/checkbox-field/checkbox-field.tsx
src/new-components/switch-field/switch-field.module.css
src/new-components/switch-field/switch-field.stories.tsx
src/new-components/switch-field/switch-field.test.tsx
src/new-components/switch-field/switch-field.tsx

This PR improves the implementation of the `SwitchField` and `CheckboxField` components, and it also introduces tests and storybook stories for both.
https://user-images.githubusercontent.com/15199/129984229-a502acb9-d0f1-414e-b00e-f09657c6cc66.mp4

Add tests, stories and improvements to the switch and checkbox components

---

.github/workflows/coverage-reporting.yml
.github/workflows/publish.yml
.github/workflows/pull_request.yml
src/index.ts

Replicating #554 in beta.
Not to be released directly. It will allow other blocked PRs to be released soon.

chore: Add step to read node version from .nvmrc file

---

CHANGELOG.md
src/components/menu/menu.stories.tsx
src/new-components/box/box.module.css
src/new-components/box/box.stories.tsx
src/new-components/box/box.test.tsx
src/new-components/box/box.tsx
src/new-components/checkbox-field/checkbox-field.stories.tsx
src/new-components/columns/columns.stories.tsx
src/new-components/columns/columns.test.tsx
src/new-components/common-types.ts
src/new-components/default-styles.less
src/new-components/divider/divider.module.css
src/new-components/divider/divider.tsx
src/new-components/heading/heading.stories.tsx
src/new-components/inline/inline.test.tsx
src/new-components/stack/__snapshots__/stack.test.tsx.snap
src/new-components/stack/stack.stories.tsx
src/new-components/stack/stack.test.tsx
src/new-components/stack/stack.tsx

The new design system for Twist features standardized dividers of different "weight": primary, secondary, and tertiary. This PR brings that system to Reactist.
To be merged without a dedicated release. It will be included in the next release.

refactor: New system of border and divider colors

---

CHANGELOG.md
src/new-components/modal/modal.module.css

Modal widths need to be different.
To be included in the next release after being merged.

Adjust modal widths

---

src/new-components/modal/modal.stories.mdx
src/new-components/select-field/select-field.module.css
src/new-components/text-area/text-area.module.css
src/new-components/text-field/text-field.module.css
stories/components/color.stories.tsx
stories/components/styles/color-story.less

A bug inadvertently introduced in #574.
No need for a CHANGELOG entry, since the bug this fixes has not been released.
To be included in the next release after being merged.

Fix border colors of the new field components

---

src/new-components/alert/alert.module.css
src/new-components/alert/alert.stories.mdx
src/new-components/alert/alert.test.tsx
src/new-components/alert/alert.tsx
src/new-components/loading/loading.stories.mdx
src/new-components/notice/notice.stories.mdx
src/new-components/notice/notice.test.tsx
src/new-components/notice/notice.tsx

Title says it all.
Will be merged without a release. To be included in an upcoming release.

Add tests, examples, and some styling fixes to Alert and Notice

---

CHANGELOG.md
src/new-components/common-types.ts
src/new-components/default-styles.less
src/new-components/text/text.module.css
src/new-components/text/text.stories.tsx

Adds "positive", green text, tone to the <Text /> component.
Does not require immediate release. Added the changes as "Upcoming" to the CHANGELOG.

feat: Add positive tone to Text component

---

CHANGELOG.md
src/new-components/base-button/base-button.module.css
src/new-components/base-button/base-button.tsx
src/new-components/button-link/button-link.stories.mdx
src/new-components/button/button.stories.mdx

See https://twist.com/a/1585/ch/81455/t/3592631/
New feature. New minor version.

feat: Allow buttons to have fully rounded/circular corners

---

CHANGELOG.md

chore: Updates changelog

---

src/components/key-capturer/key-capturer.test.tsx
src/components/key-capturer/key-capturer.tsx
stories/components/ColorPicker.stories.tsx
stories/components/Select.stories.tsx

Continues the work in #699 on a few remaining cases
To be merged if CI is green.

refactor: More modern React imports and other minor code improvements

---

CODE_OF_CONDUCT.md

Updates the `CODE_OF_CONDUCT.md` document to Contributor Covenant v2.1, and also updates the contact e-mail as communicated to the team on Twist.

docs: Update `CODE_OF_CONDUCT.md` to Contributor Covenant v2.1

---

.eslintignore
.plop/templates/component/component.module.css.hbs
.plop/templates/component/component.stories.mdx.hbs
.plop/templates/component/component.stories.tsx.hbs
.plop/templates/component/component.test.tsx.hbs
.plop/templates/component/component.tsx.hbs
.plop/templates/component/index.ts.hbs
README.md
package-lock.json
package.json
plopfile.mjs

Introduces a new tool called [plop](https://plopjs.com/), leveraged in this PR to provide an easy way to create bare-bones source files to implement a new component. The generated source files include the component implementation with sample props and styles, plus a small test file and storybook source files as well.
https://user-images.githubusercontent.com/15199/213154676-7926118f-f772-420f-baf8-cdae93efda1d.mp4
1. Run `npm install`
2. Run `npm run plop component`[^1]
3. Provide a name for your component (e.g. `dropdown select`, `NavListItem` or `sortable-table`)
4. Leave the other two prompts at their default value by pressing "Enter" twice
[^1]: Alternatively, you can `npm install -g plop` and then you can use the command `plop component` directly.
Now check the following:
No need to …

chore: Introduce new component template

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Adds a few quick notes re: Chromatic visual regression tests. 
No bump, just documentation.

chore: Add notes about Chromatic visual regression tests

---

.plop/templates/component/component.stories.tsx.hbs
.plop/templates/component/component.test.tsx.hbs
.plop/templates/component/component.tsx.hbs

Minor (stylistic) fixes to the template component that's generated via the templating command (via `plop`):
```
npm run plop component
```
Not needed.

chore: Very minor fixes to template component 

---

.github/workflows/publish.yml

See https://github.com/Doist/typist/pull/284

ci: Allow authenticated operations against the GitHub Packages registry

---

CHANGELOG.md
package-lock.json
package.json
src/menu/menu.tsx

Fixes #761 
New patch version release

fix: Using a menu both triggered by a button and by right-click

---

CHANGELOG.md
package-lock.json
package.json
src/modal/modal.module.css

Ensure the newest changes on `main` are available on `next` as well.

chore: Release 23.2.2 in 24.1.5-beta

---

CHANGELOG.md
package-lock.json
package.json

Preparing for v26.2.2 release.

chore: Bump up version to v26.2.2

---

.github/release-please-config.json

Closes #...
Include all possible changes (conventional commits) in release-please action so they are all detected for release creation. See https://github.com/commitizen/conventional-commit-types/blob/master/index.json for list of supported commits.

ci: include all changes in release creation

---

.github/release-please-config.json
.github/workflows/release-please.yml

Closes #...
Set release-please-config hidden property explicitly to false, in an attempt to fix release-please not detecting changes to create release PR.

ci: set target-branch to release-please action

---

CHANGELOG.md

This PR unify markdown format in existing CHANGELOG content to prevent automated content to be misplaced: Removed all headings.

docs: unify existing changelog content format

---

.github/dependabot.yml

Closes #...
Fix syntax on dependabot config. Ref: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

ci: fix dependabot config syntax

---

.github/workflows/release-please.yml

Closes #...
Remove code duplication and add logs to debug issue while accessing GH API.

ci: debug GH API 404 error

---

.github/workflows/deploy-storybook.yml

Closes #...
v4 does not exist. Using v3.

ci: fix version of upload-pages-artifact action

---

.github/workflows/check-semantic-pull-request.yml
.github/workflows/chromatic.yml

Closes https://github.com/Doist/reactist/issues/922

ci: Use approved versions of actions
