Doist/reactist

src/components/Modal.jsx
as it was, you could click the close button and the listeners would keep listening. 🎧
the ESC listener would only be removed when ESC was pressed. same for the overlay click.
=> removes the keydown and click listeners on componentWillUnmount.

package-lock.json, package.json
Upgrades Jest to the next major version.
Also upgrades `webpack-bundle-analyzer`. See details below.
I needed it to debug the issue fixed in #160, because Jest 23 had an issue with not printing out all the `console.log` statements executed while running tests. But since it did not cause any issues with our tests right now, and since this new version includes [a lot of other new features and improvements](https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly) I figured "why not?" 😄
This also upgrades `webpack-bundle-analyzer`, since it was the source for a significant amount of the vulnerabilities flagged by `npm audit` (there are still unresolved vulnerabilities after this, but this reduces the number a lot without much disruption, I'll probably roll out …
=> Upgrade to Jest v24

.eslintrc, src/components/utils/__tests__/TimeUtils.test.js
There's [a test case](https://github.com/Doist/reactist/blob/7782171e8b5035adf44e87dd4372b3feb8401508/src/components/utils/__tests__/TimeUtils.test.js#L67-L72) for `TimeUtils` that failed if the time zone of the computer running the test comes before `UTC`. This was because `moment`, on subtracting two days from a date that falls flat on midnight of a UTC date, you still get a date that falls flat on midnight UTC two days before. But when formatting that date, `moment` takes into account the current computer's TZ, and if this one falls before UTC, you get a date one day earlier.
Also, it adds some minimal settings for `eslint-plugin-react` that was causing a warning when running `npm run check`.
=> Fix TimeUtils test failing if run in a computer with TZ before UTC

.npmignore, CHANGELOG.md, package-lock.json, package.json
**Short description:**
In the last release parts `.git` ended up in the final release bundle which can cause problems when running `npm install` in dependent repositories as npm would detect reactist as being a repo instead of a dependency.
While fixing this I took the liberty to remove some more bloat from our published bundle and brought it down from `2.4 MB` to `470.4 kB` (packaged size)
**PR Checklist:**
=>  Introduced npmignore to slim down package and fix .git bug

src/components/__tests__/Tooltip.test.js
**Short description:**
I've added the test for Tooltip component to achive the 100% of line coverage.
**PR Checklist:**
-   [ ] Described changes in CHANGELOG.md
-   [x] Executed `npm run check` and made sure no errors / warnings were shown
-   [x] Executed `npm run test` and made sure all tests are passing
-   [ ] Bumped version in package.json
=> Add test case for Tooltip component with passing simple text

.github/workflows/publish.yml, .github/workflows/pull_request.yml, CHANGELOG.md, package-lock.json, package.json
Another attempt to fix our publish action. Basically, the problem is that we need to authenticate with npm again after authenticating with the GitHub registry in order to publish there. Not sure if the `setup-node` action inherits previous settings but its [demos](https://github.com/actions/setup-node#usage) seem to indicate so, so this is an attempt by resetting the scope and hoping an `.npmrc` will be properly created from it.
-   [ ] Executed `npm run lint` and made sure no errors / warnings were shown
-   [ ] Executed `npm run test` and made sure all tests are passing
-   [ ] Updated all static build artifacts (`npm …
=> Fix publish action

.github/workflows/publish.yml, .github/workflows/pull_request.yml, CHANGELOG.md, package-lock.json, package.json
With @doist/prettier-config now released on [npm](https://www.npmjs.com/package/@doist/prettier-config/v/3.0.5), we can remove all the hoops we had to jump to get dependencies installed on CI.
The `npm prepare` script has also been removed, as it was building tarballs with different checksums when publishing to both npm and GitHub. Not sure if this solves it but at least we'll only build once now.
-   ~~Added tests for bugs / new features~~
-   ~~Updated docs (storybooks, readme)~~
-   ~~Executed `npm run lint` and made sure no errors / warnings were shown~~
-   ~~Executed `npm run test` and made sure all tests are passing~~
-   [x] Bumped version in `package.json`
-   ~~Updated all static build artifacts (`npm run build-all`)~~
=> Reinstall @doist/prettier-config and update release workflow

src/components/Select.tsx
`Select.onChange` callback is currently typed with `string | number | undefined` as return value, but value type will always be `string`.
It only changes types. The new type narrower, so the change is non-breaking.
=> More accurate type of onChange callback.

src/components/Button.tsx, src/components/__tests__/Modal.test.tsx
*remove close prop from button, since it is deprecated
*remove tests checking for unmounting when child with close prop is clicked
Closes #198 
1. Removed the close prop from the button component file. 
2. After the removal, 2 tests in the modal component were failing
* the tests were checking for unmounting when a child component with the close prop was clicked - removed those 2 tests since we are removing the close prop from the button
-   [x] Executed `npm run lint` and made sure no errors / warnings were shown
-   [x] Executed `npm run test` and made sure all tests are passing
-   [ ] Updated all static build …
=> Remove close prop from button (#198)

CHANGELOG.md, package.json
This fixes sideEffects configuration to allow CSS files to be imported from reactist.
-   [x] Bumped version in `package.json`
This is a bugfix change.
=> Fix wrong sideEffects

.eslintrc
Remove react/sort-comp rule in preparation to adopt shared config, as discussed [here](https://github.com/Doist/eslint-config/issues/28).
Lint only, no need to publish.
=> chore: Remove react/sort-comp eslint rule.

.eslintrc, src/components/Popover.tsx, src/components/Tooltip.tsx, src/components/__tests__/KeyCapturer.test.tsx, src/components/__tests__/Menu.test.tsx, src/components/__tests__/Popover.test.tsx
no-unsafe-* lint rules are important, because violations have potential to produce a runtime crash. This PR re-enables all no-unsafe rules in main codebase, but allow exception in storybook and tests (hard to fix there due to older storybook and complicated mock typing).
Popover and Tooltip are not 100% strict and a couple of violations are ignored there. I never figured out how to retrict `children` type(s).
Only affects linting / types, does not need a release.
=> Re-enable no-unsafe-* rules in main codebase

.eslintrc
Remove linebreak-style rule, because it is already covered by prettier/prettier ('lf' linebreak is default since prettier 2.0).
Only affects lint, no release needed.
=> Remove linebreak-style rule already covered by prettier.

.eslintrc, src/components/__tests__/Tooltip.test.tsx
Re-enable expect-expect lint rule. There doesn't seem to be good way to avoid it triggering in case of delegating test to another function, but it's better to address on per-case basis than disable everywhere.
https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/expect-expect.md
Only affects lint.
=> Re-enable expect-expect lint rule.

package-lock.json, package.json
Remove (now unused) babel-eslint.
This is internal change, no need to version.
=> chore: Remove babel-eslint.

package.json, scripts/build.sh, scripts/organize-styles.sh
In recent product PRs we've fixed our local reactist setup. This went well for code changes but didn't work for style changes. Also it required to run `npm run build` before running the watch mode with `npm start`. With this PR this gets fully fixed, we no longer need to run build before the watch mode and we can change styles and see them reflected in the apps.
I tried to find a solution that is not based on bash scripts but integrates with tsdx / rollup but couldn't make it work with the copy and delete plugins (the order of these plugins cannot be specified in the way we need it because the hooks are not granular enough).
You can test this PR by running `npm run clean`, then `npm start` and then start up todoist or twist web and see your changes reflected immediately.
=> Organize styles during watch mode

.eslintrc, src/components/Dropdown.tsx, src/components/Modal.tsx
Fix `@typescript-eslint/unbound-method` rule violations and re-enable the rule in preparation to adopt shared [eslint-config](https://github.com/Doist/eslint-config). For context, see discussion in [here](https://github.com/Doist/twist-web/pull/2783).
The fix uses class property syntax. I know we've had some problems with transpiling it in other projects, so please double-check it's ok. I've run the tests and stories and checked output in es directory.
It only affects internals and does not require release of its own.
=> Fix @typescript-eslint/unbound-method by using class property arrow.

src/components/menu/type-helpers.ts
Closes #421 
Not having 'as' attribute defined, results into TT not being defined and probably allow any props as result. I added as default type for TT 'ComponentType', which looks making duplicates but working well.
I deleted the second line which then become useless. 
Here some examples:
-   [x] Executed `npm run validate
` and made sure no errors / warnings were shown
=> Fix type definition for MenuItem when no as attribute

.eslintignore, .eslintrc, package-lock.json, package.json, src/components/avatar/utils.ts, src/components/button/button.tsx, src/components/modal/modal.test.tsx, src/components/time/time-utils.ts, stories/components/ButtonStory.tsx, stories/components/MenuStory.tsx, stories/components/ModalStory.tsx
Adopt @doist/eslint-config. WIP.
It is internal cleanup, no need to release.
=> refactor: Adopt @doist/eslint-config

tsconfig.dist.json
When using the Button component from the latest beta releases, a mysterious `css` prop has been declared as required. This turns out to be a merged interface on both `React.DOMAttributes` and `JSX. IntrinsicAttributes` from emotion 10, which is included in Storybook:
https://github.com/emotion-js/emotion/blob/ab535a8c7a0dcbbb6af310634eb3cee4bc2f8e2c/packages/core/types/index.d.ts#L86
The solution now seems to be to omit anything storybook-related from the output. As our stories still need to be type-checked during development, they are only excluded in `tsconfig.dist.json`
- Pull the latest beta branch and run `npm run build`. In another project that has Reactist installed, run `npm link ../reactist`
- Use the `Button` component in the project and let type-checking run, either in your …
=> fix: Exclude emotion's css prop from exported typedefs

package-lock.json, package.json
With #464 I added patch-package in order to patch rollup-plugin-style, however when being installed as a package with `npm ci`, patch-package will not be available and the install will exit.
This moves patch-package to our dependencies so that it'd be available. When installing as a package, it will omit patching dev dependencies, so other than the extra package being installed, there should be no additional consequences: [ref](https://docs.npmjs.com/cli/v6/using-npm/scripts#prepare-and-prepublish)
The alternative is to run patch-package with the [`prepare` script](https://docs.npmjs.com/cli/v6/using-npm/scripts#life-cycle-scripts), which sounds like it covers all the scenarios that we would want it to run in, however, patch-package used to recommend the prepare script and have since …
=> fix: Move patch-package to dependencies

src/components/button/button.less, src/components/button/button.tsx, src/components/dropdown/__snapshots__/dropdown.test.tsx.snap
Add `aria-disabled` to the `Button` component to ensure its state is read by screen readers.
The current implementation using `disabled` is ignored by screen readers and so I wanted to experiment a bit with this component to make it more accessible. By adding `aria-disabled`, simply changing the CSS selector which already applied opacity anyway, and conditionally blocking `onClick` events, the button is now picked up by screen readers whilst it maintains its disabled state look. 
The change requires no changes to any components making use of the button since it still expects a `disabled` prop. The only difference now is that the prop is only used to determine whether `onClick` should fire or `aria-disabled` should be true or false.
- Run storybook 
-   [ ] Inspect any of the buttons …
=> Make disabled button component more accessible through aria-disabled

CHANGELOG.md, package-lock.json, package.json
Upgrading to 9.1.4 ahead of a new release to include changes made to the disabled `Button` component in [this](https://github.com/Doist/reactist/pull/509) PR.
A new version 9.1.4 will be published
=> chore: Upgrade version to 9.1.4

.github/workflows/temp-default-branch-migration.yml
This PR introduces a temporary action ([default-branch-migration](https://github.com/marketplace/actions/default-branch-migration)) to help with the default branch migration from `master` to `main`.
The changes here are pretty much copy/paste from the documentation, and there's nothing to test. That's why I'm opening this PR and merge it without tagging anyone.
=> chore: Add temporary action for default branch migration (#3576)

.github/actions/default-branch-migration/Dockerfile, .github/actions/default-branch-migration/action.yml, .github/actions/default-branch-migration/entrypoint.sh, .github/workflows/temp-default-branch-migration.yml
Unfortunately, the original `default-branch-migration` action seems to have an issue when trying to keep `dev` and `main` in sync. This PR moves the action code into the repository so that we can tweak it to our liking and fix any issues (such as the one just described).
=> chore: tweak and fix `default-branch-migration` action

.github/ISSUE_TEMPLATE/Feature.md, .github/actions/default-branch-migration/Dockerfile, .github/actions/default-branch-migration/action.yml, .github/actions/default-branch-migration/entrypoint.sh, .github/workflows/codeql-analysis.yml, .github/workflows/coverage-reporting.yml, .github/workflows/temp-default-branch-migration.yml, CONTRIBUTING.md, stories/reactist/Reactist.stories.mdx
An attempt to change all `dev` references I could find to `main`. The more critical ones are scripts and CI related files (GitHub Workflows / Azure Pipelines). The less critical ones, documentation files.
Please review carefully, and let me know if you think I've missed some references.
If all pipelines and statuses checks are green, it should be good to go. But the real test will be after this is merged.
=> chore: Change all `dev` branch references to `main`

CHANGELOG.md, package-lock.json, package.json, src/components/keyboard-shortcut/__snapshots__/keyboard-shortcut.test.tsx.snap, src/components/keyboard-shortcut/keyboard-shortcut.test.tsx, src/components/keyboard-shortcut/keyboard-shortcut.tsx
This makes a small tweak to `KeyboardShortcut`.
The component already has a `translateKey` prop, where you can define a translation function,
that will display certain modifiers in a different way.
So far, this was not possible with the `Super` key.
In this PR, I treat it as a `special` key to be translated, just like `Cmd` and others.
This way, the calling component gets a chance to translate the `Super` key. 
On Windows, super is an alien term, so we want to translate it to `Win` or `Windows` there,
this PR enables that by ensuring `translatekey` is called for `Super` key as well.
-   [x] Described changes in …
=> Ensure Super key gets sent to translation function

stories/components/Modal.stories.mdx
During the upgrade to Storybook 6 and the shift to MDX stories, we noticed that the prop types for the `Modal` story weren't inferred due to its structure (a component with subcomponents with their own props and types as its type). 
After a lot of researching online and creating a discussion in [Storybook's repo](https://github.com/storybookjs/storybook/discussions/15573), we have yet to find a way to automatically infer prop types of this component. Two workarounds were: **a)** inferring prop types from one of the actual stories i.e. Playground and not the component or **b)** manually set these props and their descriptions (the former wouldn't handle this). In this PR, I've attempted option **b.** 
Granted it may not be the best solution, as any changes made to the `Modal` component will …
=> fix: Add prop table for modal story

src/new-components/box/box.test.tsx, src/new-components/columns/columns.test.tsx, src/new-components/columns/columns.tsx, src/new-components/inline/inline.test.tsx, src/new-components/stack/__snapshots__/stack.test.tsx.snap, src/new-components/stack/stack.test.tsx, src/new-components/test-helpers.tsx
Adds the first new set of tests for the new design system components. I left it short, focusing on the layout components mostly, to make it easier to digest. And also to validate the approach.
Granted, most of these tests are not giving us the full confidence we'd expect. It all works by validating that certain class names are being added to the components, but we could still break things when touching the CSS files. My aim is to eventually add either visual regression tests, or Cypress component tests. I experimented with the latter, but I was not able to make it work in the short term. These tests are still valuable as they validate the logic inside JS code that decides what class names to apply.
-   [ …
=> Add tests for the layout-related components

src/new-components/box/box.tsx, src/new-components/stack/stack.stories.tsx, src/new-components/stack/stack.test.tsx, src/new-components/stack/stack.tsx, src/new-components/storybook-helper.tsx
Adds a new `align: 'left' | 'center' | 'right'` prop to `Stack` to allow horizontally aligning the stack items.
Not to be released yet. This is being merged in a base PR where we're gathering some of the changes these days into a single weekly-ish release schedule.
https://user-images.githubusercontent.com/15199/129598982-b14916ec-c1bb-49ba- …
=> Add Stack align prop to align items horizontally

src/new-components/box/box.stories.tsx, src/new-components/box/box.test.tsx, src/new-components/columns/columns.stories.tsx, src/new-components/columns/columns.test.tsx, src/new-components/columns/columns.tsx, src/new-components/inline/inline.stories.tsx, src/new-components/inline/inline.test.tsx, src/new-components/responsive-props.ts, src/new-components/stack/stack.stories.tsx, src/new-components/stack/stack.test.tsx, src/new-components/test-helpers.tsx
Changes how we provide responsive props, from this:
```jsx
<Component prop={[mobileValue, tabletOrLargerValue, desktopOrLargerValue]} />
```
to an object-like notation instead:
```jsx
<Component prop={{ mobile: '…', tablet: '…', desktop: '…' }} />
```
See https://twist.com/a/1585/ch/190200/t/2693346/c/69556610
=> Change how responsive props are provided

src/index.ts, src/new-components/checkbox-field/checkbox-field.tsx, src/new-components/hidden-visually/hidden-visually.module.css, src/new-components/hidden-visually/hidden-visually.test.tsx, src/new-components/hidden-visually/hidden-visually.tsx, src/new-components/hidden-visually/index.ts, src/new-components/hidden/hidden.module.css, src/new-components/hidden/hidden.stories.tsx, src/new-components/hidden/hidden.test.tsx, src/new-components/hidden/hidden.tsx, src/new-components/hidden/index.ts, src/new-components/switch-field/switch-field.tsx
Adds a couple new components to hide content in a declarative way:
- `Hidden` used to hide content on certain responsive screen sizes, and/or in print mode.
- `HiddenVisually` used to visually hide content from the screen while still having it available for assistive technologies.
To be released soon in bulk with other changes being …
=> New components for hiding content in various ways

src/new-components/box/box.module.css, src/new-components/box/box.test.tsx, src/new-components/box/box.tsx, src/new-components/heading/heading.module.css, src/new-components/heading/heading.stories.tsx, src/new-components/heading/heading.test.tsx, src/new-components/heading/heading.tsx, src/new-components/responsive-props.ts, src/new-components/text/text.module.css, src/new-components/text/text.stories.tsx, src/new-components/text/text.test.tsx, src/new-components/text/text.tsx, src/utils/polymorphism.ts
Most notably, this PR adds `textAlign` support for `Box`, and uses it to implement a `align` prop in both `Heading` and `Text`.
In addition to that, it adds tests for both the `Heading` and `Text` components, and new stories to showcase the `align` responsive feature. It also adds jsdoc comments to the props for each of these two components.
-   [ ] Updated all static build artifacts (`npm run …
=> Text and Heading tests, new stories and improvements

.github/workflows/coverage-reporting.yml, .github/workflows/publish.yml, .github/workflows/pull_request.yml, package-lock.json, package.json, src/components/menu/menu.test.tsx
Adds a step to read the node version from `.nvmrc` and then uses the outputted `NODE_VERSION` across other workflow files. PRs have been failing as the variable was being used outright without having the step to read from the file first.
Note: I had a test error regarding an irrelevant `await` operator on `userEvent`, I've fixed this in this branch too since it was preventing me from pushing.
-   [ ] CI should be green, especially coverage reporting
=> chore: Add step to read node version from .nvmrc file

CHANGELOG.md, src/new-components/tabs/tabs.stories.mdx, src/new-components/tabs/tabs.test.tsx, src/new-components/tabs/tabs.tsx
This uses Ernesto's new `polymorphicComponent` helper (which works awesome 👏) to add support for an `as` prop to `TabPanel`, which allows it to render any element/component users specify.
Example taken from the new story - `TabPanel` being rendered as a `Box` and a `section`:
Next beta
=> feat: Support polymorphism with `TabPanel` component

CHANGELOG.md, src/new-components/modal/modal.module.css
There are two modes by which modals handle vertical space (not introduced in this PR, is what we've already have):
1. Some modals expand to fill most of the viewport height (`height="expand"`).
2. Other modals fit their content's height (`height="fitContent"`).
> **Note:** in both cases the modal body's content is set to scroll if it becomes larger than the larger height they can fill.
This PR does not change what modes we have. It only changes how the mode `height="fitContent"` positions the modal vertically.
- **Before this PR**, these `fitContent` modals were vertically centred all the time. This caused a problem with modals that have content that causes them to change their height dynamically. These modals would then jump in both directions, shrinking and expanding as the content …
=> Better adjust a modal's vertical position when in fitContent mode

CHANGELOG.md, src/new-components/base-button/base-button.module.css
- I realized while using the new snooze menu button in twist that the new button component should stay highlighted (as if it were hovered) when used as a menu button and that menu is expanded.
- Another improvement here is borrowed from Twist buttons in the onboarding pages: the colour changes now feature a transition. It is a very slight effect, but it's a nice touch. For instance, when the button's background colour changes when hovered, the button colour changes.
-   [ ] Updated all …
=> Button style improvements

CHANGELOG.md, src/new-components/base-button/base-button.module.css, src/new-components/button-link/button-link.stories.mdx, src/new-components/button/button.stories.mdx
Buttons with a visual text label (i.e. buttons that are not icon-only buttons) now have a minimum width set, so they don't get too small for extremely short labels.
To be merged as is. It will be included in an upcoming release that we'll prepare soon, but not in this PR.
=> Button min width

CHANGELOG.md, src/new-components/box/box.module.css, src/new-components/box/box.stories.tsx, src/new-components/box/box.tsx, src/new-components/box/width.module.css, src/new-components/default-styles.less, src/new-components/password-field/password-field.stories.tsx, src/new-components/select-field/select-field.stories.tsx, src/new-components/storybook-helper.tsx, src/new-components/text-field/text-field.stories.tsx
This PR enhances does two main things:
- Introduces CSS variables that control what size is used for the semantic values for a Box's `maxWidth` and `minWidth`.
- Enhances the `width` prop of `Box` with more supported values:
- The same semantic values from `maxWidth` and `minWidth` (`xsmall` to `xlarge`)
- Values encoding predefined CSS values for the `width` CSS property (`minContent`, `maxContent`, `fitContent`).
Part of this is prompted by a need that was raised in https://github.com/Doist/todoist-web/pull/3477.
-   [ ] Bumped version in `package.json` and `package-lock.json` …
=> Box width/maxWidth/minWidth improvements

src/new-components/default-styles.less, src/new-components/heading/heading.module.css, src/new-components/tabs/tabs.module.css, src/new-components/text-link/text-link.module.css, src/new-components/text/text.module.css, stories/components/color.stories.tsx
Title says it all.
These variables were unused for the most part. They are not used in Twist. And most uses here were only the declaration and the mention in the documentation. The handful of cases in which they were used elsewhere, were to declare the value of some other variable. I copied the literal value to those other variable declarations, removing the middle man.
The new colour naming scheme does not use these variables anyway, hence my reasoning to do this.
Not much of the entries below apply to this PR. Probably none.
-   [ ] Bumped version in `package.json` and …
=> Remove unused CSS variables

CHANGELOG.md, src/new-components/inline/inline.tsx, src/new-components/modal/modal.test.tsx, src/new-components/modal/modal.tsx
Closes #613
Supersedes PR #614 
This PR performs the following changes on the `ModalActions` component:
- ignore `null` children
- flatten children wrapped in React fragments
- removes the unneeded extra div wrapping each child element (following the same logic described [here](https://github.com/Doist/reactist/wiki/Simplified-markup-of-the-Stack-and-Inline-components)).
Additionally, this removes an extra `Box` wrapping the main element rendered by `Inline`. I was surprised to see it, and did several manual testing (both in the storybook, and running twist-web with my local version of Reactist with these changes in place) and, as I suspected, this outer `div` is not needed.
-   [x] Executed `npm run …
=> fix: Various fixes to the `ModalActions` component

CHANGELOG.md, src/new-components/default-styles.less, src/new-components/tabs/tabs.module.css
Recently it came to light, on https://github.com/Doist/Polish/issues/622, that the default medium font-weight (`500`) doesn't match the `600` value defined in the design system mockups.
Furthermore, the `Text` component defines `semibold` as reactistis medium font-weight:
https://github.com/Doist/reactist/blob/4d7c3a2646e634d5ceb75f02752ad812a2ee7ee4/src/new-components/text/text.module.css#L18-L20
Although `semibold` is commonly attributed to a font-weight value of `600` and not `500`.
This PR normalizes this mismatch by bumping the value to `600`. The `Text` and `Button` components are affected by this change.
Additionally, as per the [Tabs spec](https://www.figma.com/file/LYlWNzvhMDh907l07mPPQk/Product---Web?node-id=4693%3A175143), tabs should have `medium` font-weight and not `normal`. …
=> style: Update default medium font-weight to 600

CHANGELOG.md, src/new-components/text-area/text-area.tsx
Closes #612 
Add optional rows prop to text area
=> Add rows type to text area

CHANGELOG.md, src/new-components/box/box.stories.tsx, src/new-components/box/box.test.tsx, src/new-components/box/box.tsx, src/new-components/heading/heading.stories.tsx, src/new-components/heading/heading.test.tsx, src/new-components/text/text.stories.tsx, src/new-components/text/text.test.tsx
Closes https://github.com/Doist/reactist/issues/618
The current behaviour of the text align prop is that it defaults to `start` when not provided, and does not apply a CSS class to the element when text align is equal to `start`. This generally works as expected for the default case, however it makes it impossible to actually add the CSS property `text-align: start;` to these box elements.
The solution for this was to remove the default value of the `textAlign` prop, and to also remove the special handling for the `start` value. This results in the same default behaviour as previously (no class is added to the element), while ensuring that providing the value "start" adds the CSS class and resulting property as expected.
This change also influences the `Heading` and `Text` components …
=> fix: [Box] Using "start" as a value for textAlign doesn't add text alignment

CHANGELOG.md, src/new-components/modal/modal.test.tsx, src/new-components/modal/modal.tsx
This PR doesn't implement any functional change, only updates the Modal Header layout. The problem that it solves is that when the close button is hidden (its prop set `false`/`null`/`undefined`), the button column is rendered, although the button isn't. The column follows the parent `Columns` component spacing specification and renders a `large` spacing, even though there's isn't actual content rendered inside it.
The following screenshot exemplifies the problem, marking the extra column in a different color.
<a href="https://codesandbox.io/s/clever-yalow-675wis">
alt="extra-spacing" class="screenshot">
</a>
[^1]
[^1]: https://codesandbox.io/s/clever-yalow-675wis
The solution is to not render the column when the button is hidden.
-   [X] Added tests for bugs / new features
-   [ ] …
=> fix: Hide Modal Header close button column when the button is not rendered

CHANGELOG.md, src/new-components/base-button/base-button.tsx
Exposes the  `gapSize` prop from `<Tooltip>` as a `tooltipGapSize` prop in `<Button>`. This is required by the new editor toolbar:
We need to push the tooltip further up a bit.
New feature required for the new editor toolbar, to be released as soon as it's merged.
=> feat: Allow buttons to customize tooltip `gapSize`

CHANGELOG.md, src/new-components/box/box.module.css, src/new-components/box/box.tsx
Split from https://github.com/Doist/twist-web/pull/4667, this adds the `alignSelf` option so that `Box`s rendered as flex children can be aligned differently from their siblings or how the parent flex container defined its `alignItems`.
Minor release
=> feat: Add `alignSelf` to `<Box>`

CHANGELOG.md, src/new-components/base-button/base-button.module.css, src/new-components/base-button/base-button.tsx, src/new-components/button-link/button-link.stories.mdx, src/new-components/button-link/button-link.test.tsx, src/new-components/button/button.stories.mdx, src/new-components/button/button.test.tsx, src/new-components/modal/modal.tsx
During my work in the new Task details view in Todoist, I've noticed the need for buttons to be optionally expanding their width instead of growing as little as needed to have their label fit. Also, when in this mode, we want to customize the label alignment as well.
I recommend looking at the diff with whitespace changes hidden.
Using storybook (`npm run storybook`), do the following:
-   [ ] ~~Bumped version in `package.json` and `package-lock.json` (`npm --no-git-tag-version version <major|minor|patch>`) [ref](https://docs.npmjs.com/cli/v6/commands/npm-version)~~
-   [ ] …
=> feat: <Button width="full" align="start|center|end">

CHANGELOG.md, src/new-components/loading/loading.stories.mdx, src/new-components/loading/loading.test.tsx, src/new-components/loading/loading.tsx
Adds a `xsmall` size, 16px, option to the `<Loading />` component.
Does not require immediate release. Added the changes as "Upcoming" to the CHANGELOG.
=> feat: Add xsmall size to Loading component

CHANGELOG.md, src/new-components/text-link/text-link.module.css
Apply TextLink color through `--reactist-text-link-color`.
-   [ x] Executed `npm run validate` and made sure no errors / warnings were shown
-   [ x] Described changes in `CHANGELOG.md`
Does not require immediate release. Added the changes as "Upcoming" to the CHANGELOG.
=> fix: set TextLink color using CSS variable

.github/workflows/publish.yml, .npmrc, CHANGELOG.md, package-lock.json, package.json
In #661 I added a `@doist:registry` entry in the project's .npmrc, forcing installs for Doist's dependencies to be sourced from the npm registry rather than GH, but this broke the release script. In this PR, the `@doist:registry` line is removed before initiating a release.
`💚 Show`
Patch
=> chore: Remove registry configs before publishing

src/components/menu/menu.less, src/components/menu/menu.tsx
Ariakit's menu renders the menu list with a `menubar` role instead of `menu` in Safari due to a VoiceOver issue. As we leverage the role attribute for styling, this resulted in them not being applied.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/8531248/171023167-33daab9a-00c0-47a6-ac9a-addf171a624a.png)|![image](https://user-images.githubusercontent.com/8531248/171023070-a60fddf0-7cee-428c-b633-feca7536ed57.png)|
-   [ ] Bumped version in `package.json` and `package-lock.json` (`npm --no-git-tag-version version <major|minor|patch>`) …
=> fix: Add missing menu styling for Safari

CHANGELOG.md, src/new-components/base-field/base-field.module.css, src/new-components/base-field/base-field.tsx, src/new-components/default-styles.less, src/new-components/password-field/password-field.stories.tsx, src/new-components/password-field/password-field.test.tsx, src/new-components/password-field/password-field.tsx, src/new-components/select-field/select-field.module.css, src/new-components/select-field/select-field.test.tsx, src/new-components/select-field/select-field.tsx, src/new-components/text-area/text-area.module.css, src/new-components/text-area/text-area.stories.tsx, src/new-components/text-area/text-area.tsx, src/new-components/text-field/text-field.module.css, src/new-components/text-field/text-field.stories.tsx, src/new-components/text-field/text-field.test.tsx, src/new-components/text-field/text-field.tsx, src/new-components/text/text.module.css
- [Discussion in Twist](https://twist.com/a/1585/ch/81455/t/3484406/)
- Supersedes #659 (which only added error messages)
Review manually the live components in the various new stories titled "Message Tone Story" in storybook
<details>
<summary><strong>Demo</strong></summary>
<table><tr><td>
</td></tr></table>
</details>
New minor release
=> feat: Add a semantic message and tone to most field components

CHANGELOG.md, src/new-components/base-field/base-field.module.css, src/new-components/base-field/base-field.tsx, src/new-components/password-field/password-field.module.css, src/new-components/password-field/password-field.stories.tsx, src/new-components/password-field/password-field.tsx, src/new-components/text-area/text-area.module.css, src/new-components/text-area/text-area.stories.tsx, src/new-components/text-area/text-area.tsx, src/new-components/text-field/text-field.module.css, src/new-components/text-field/text-field.stories.tsx, src/new-components/text-field/text-field.tsx
This would allow use the Reactist component for the views that use this different style of text fields (e.g. Todoist and Twist login/onboarding pages).
- [Related discussion in Twist](https://twist.com/a/1585/ch/190200/t/3456577/c/76152665)
This functionality is almost purely style-related[^1], it is a bit pointless to test in jest. I could test that the correct classes are being added here and there, but that provides very little confidence, since so much could be broken by changes in the style rules applied to those classes.
Given my upcoming plans to work in visual regression testing, I'm putting my bets on that for really testing this in a much better and confident way. But if you think there's something we could do that would add value, let me know.
[^1]: Even some interaction …
=> feat: Introduce a "bordered" variant for all text-like fields

CHANGELOG.md, src/new-components/text-field/text-field.module.css
Fixes the input padding for `<TextField variant="bordered" />`.
Before:
After:
=> fix: Reset input padding for bordered TextField

CHANGELOG.md, src/new-components/base-button/base-button.module.css, src/new-components/base-button/base-button.tsx, src/new-components/button-link/button-link.test.tsx, src/new-components/button/button.test.tsx
The main motivation for this PR was to remove the forced 100% width on button labels. However, in doing so I also noticed an opportunity to remove some custom CSS in favour of using props on existing components. The 100% width on button labels introduced a regression that requires custom styling as highlighted [here](https://github.com/Doist/reactist/pull/647/files#r875136060)
- Run storybook, and compare https://doist.github.io/reactist/?path=/docs/design-system-button--full-width to http://localhost:6006/?path=/docs/design-system-button--full-width
-   [ ] Bumped version in …
=> refactor: Make label full width configurable

CHANGELOG.md, src/new-components/base-button/base-button.tsx, src/new-components/button/button.test.tsx
The `tooltipGapSize` button prop was introduced in #636, but was challenged shortly afterwards, as not being a good course of action. See https://github.com/Doist/reactist/pull/636#issuecomment-1098598788.
However, the reason for needing it was related to the fact that icon-only buttons are too aggressive in assuming they should use the `aria-label` for the tooltip if no tooltip is given. This PR makes it so that icon-only buttons only fall back to use `aria-label` as tooltip if the tooltip is really omitted (that is, the prop is not given at all, or given with value `undefined`). If the `tooltip` prop is given, but with a falsy/empty value, the implicit tooltip is now omitted, allowing consumers of the button to fully own the rendering of the tooltip, or to really suppress it if they …
=> BREAKING: Remove Button's tooltipGapSize prop

CHANGELOG.md, src/components/tooltip/tooltip.test.tsx, src/components/tooltip/tooltip.tsx
This fixes an issue where if you used a tooltip anchor with an `as` prop, it gets doubly applied, creates a nested element, and loses the anchor's children in the process 😬
Example:
```TSX
<Tooltip content="Some helpful info">
<Box as={Link} to="/help">Hover me for info</Box>
</Tooltip>
```
...would result in something like:
```TSX
<a href="/help">
<a href="/help"> />
<a>
```
You could test this in storybook by undoing the fix, then using `<Box as={Button}>` as an anchor.
-   [ ] Bumped version in `package.json` and `package-lock.json` (`npm --no-git-tag-version version …
=> fix: Ensure Tooltips work with anchors that have an `as` prop

CHANGELOG.md, src/new-components/tabs/tabs.module.css, src/new-components/tabs/tabs.stories.mdx, src/new-components/tabs/tabs.tsx
This changes the `Tab` component's API and drops a few variations that we no longer use. The `color` prop has been removed, and `variant` now accepts `themed` and `neutral` as valid options.
More details are in https://github.com/Doist/Issues/issues/6854 and https://twist.com/a/1585/inbox/t/3688056/.
Major
=> breaking: Support `themed` and `neutral` Tab variations

CHANGELOG.md, src/new-components/tabs/tabs.module.css, src/new-components/tabs/tabs.stories.mdx
Reduces the tab's height as requested at https://twist.com/a/1585/ch/1329/t/3688056/c/78152818
Minor
=> feat: Reduce default height for Tabs, expose custom property for customization

CHANGELOG.md, src/components/menu/menu.less, src/components/menu/menu.stories.tsx
Closes https://github.com/Doist/Issues/issues/7375
Applies `min-height: 44px` and `max-height: var(--popover-available-height)` to `.reactist_menulist` in order to allow the menu list popover to scroll when it's height is greater than the viewport.
The min-height is set according to the [minimum target size for pointer inputs](https://www.w3.org/TR/WCAG21/#target-size).
This fixed is based on the ariakit [menu example implementation](https://github.com/ariakit/ariakit/blob/9b2af70dc86fa767ffb8fb268ade591bc988cce7/packages/ariakit/src/menu/__examples__/menu/style.css#L4).
-   Run the Reactist storybook
- Navigate into the `Components > Menu > Simple Menu Example` canvas tab.
- Expand the Simple Menu
- …
=> fix: Set max-height on reactist_menulist

CHANGELOG.md, src/new-components/base-field/base-field.tsx, src/new-components/password-field/password-field.stories.tsx, src/new-components/select-field/select-field.stories.tsx, src/new-components/text-area/text-area.stories.tsx, src/new-components/text-area/text-area.test.tsx, src/new-components/text-area/text-area.tsx, src/new-components/text-field/text-field.stories.tsx, src/new-components/text-field/text-field.test.tsx
A handful of improvements and fixes related to field components. Most prominently:
1. Allow them to render without a label.
- This was already technically possible, but it rendered a gap at the top of the component, the spacing between it and its labels. That gap is now gone if there are no labels to render.
- The label prop is still not optional. Users must be explicit about not wanting a label by passing `label=""` or `label={null}`
2. Add tests for `TextArea` and a couple of fixes uncovered by the new tests.
- See `CHANGELOG` for details …
=> feat: Field and textarea components improvements

CHANGELOG.md, src/new-components/text-area/text-area.module.css, src/new-components/text-area/text-area.stories.tsx, src/new-components/text-area/text-area.tsx
Fixes an issue that @engfragui brought up before in the context of their use of Reactist TextArea in the adaptive cards components. The issue then was resolved differently, due to certain circumstances with adaptive cards. But the issue remained. Now it appears again, and it's blocking me from merging https://github.com/Doist/todoist-web/pull/4988.
So here's the fix.
The text area is incompatible with horizontal resizing alongside us wanting it to stretch horizontally, which is what we want most of the time. This very text area in GitHub where I'm typing this has the same problem. So the fix was to add `width: 100%; resize: vertical;` to the `<textarea />` element of the `<TextArea />` component. Everything else in the diff is not about the fix, but a refactor of the CSS modules class …
=> fix: TextArea now controls the width and only allows resizing vertically

.storybook/main.js, CHANGELOG.md, src/new-components/checkbox-field/checkbox-field.stories.mdx, src/new-components/checkbox-field/checkbox-field.test.tsx, src/new-components/checkbox-field/checkbox-field.tsx
This change enhances the `label` property in the `CheckboxField` component to be of the type `React.ReactNode`, allowing one to use a React component as label, instead of only a `string`.
This will permit that the checkbox, icon, and text label, in the items such as the ones below, are all clickable (thus toggling the check state on and off):
-   [ ] Updated all static build artifacts (`npm run …
=> feat: Enhance the `label` property in `CheckboxField` to be of the type `React.ReactNode`

package.json
Add support for Node v18 and npm v9 to the `engines` field on `package.json`
=> chore: Add support for Node v18 and npm v9

CHANGELOG.md, src/components/menu/index.ts, src/components/menu/menu.stories.tsx, src/components/menu/menu.test.tsx, src/components/menu/menu.tsx
Closes https://github.com/Doist/Issues/issues/7077
This adds a `<MenuContextMenuTrigger>` component to allow an element to open a menu as a context menu.
Reference: https://ariakit.org/examples/menu-context-menu
Minor
=> feat: Add support for Menu as context menu

CHANGELOG.md, src/components/menu/index.ts, src/components/menu/menu.test.tsx, src/components/menu/menu.tsx
This fixes submenus which were previously broken. The main cause is the `<FocusLock>` on the menu, as it causes the menu to be closed as soon as the submenu's menu button is hovered over. It was originally added with https://github.com/Doist/reactist/pull/686 to ensure menus can be used properly when rendered within a modal, but I couldn't see what's broken when testing it with the focus lock removed now.
Ariakit example: https://ariakit.org/examples/menu-nested
-   [ ] Bumped version in `package.json` and `package-lock.json` (`npm --no-git-tag-version version …
=> fix: Allow submenus to be rendered and support keyboard navigation

.github/workflows/coverage-reporting.yml, .github/workflows/publish.yml, .github/workflows/pull_request.yml
`set-output` is being deprecated and will cause failures June 2023. Updated to the recommended approach.
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://github.com/Doist/infrastructure-backlog/issues/481
=> ci: Remove deprecated set-output usage

CHANGELOG.md, src/new-components/modal/modal.test.tsx, src/new-components/modal/modal.tsx
We need a way for consumers to define custom classes on the new Modal's overlay. This is needed to support custom styling for the overlay (eg. both the command menu, and quick add modal in Todoist), and for adding custom animations.
Patch
=> feat: Allow defining a custom class on the Modal's overlay

src/new-components/modal/modal-stories-components.tsx, src/new-components/modal/modal.test.tsx, src/new-components/modal/modal.tsx
Certain Todoist modals are not dismissable if their overlay is clicked. We're adding here a new prop, `hideOnOverlayClick`, to control that behavior.
Minor
=> feat: Add support for preventing Modal from hiding when clicking overlay

src/new-components/select-field/select-field.module.css, src/new-components/select-field/select-field.stories.tsx, src/new-components/select-field/select-field.test.tsx, src/new-components/select-field/select-field.tsx
Adds `variant` support to `SelectField` similar to what we've done in `TextField`. I'm recently seeing more product mock-ups containing a bordered variant of the `SelectField` ([ref](https://www.figma.com/file/KCVzX67egZgoeXFzjE62wc/TD-Multiplayer-First-Mile-(Design)?node-id=1199%3A238458&t=faCKgFpYHKsAfYSG-0), [ref](https://www.figma.com/file/ei8tJRO09v5MUXpLgm6ZT0/TW-Delight%3A-Onboarding?node-id=346%3A124735&t=xMdkxq2OHp7eFDri-0)). Given this, along with the fact `TextField` already supports it, I couldn't see a reason why not to bring support to this component too.
- Select the `bordered` variant of the `SelectField`
- …
=> feat: feat: Add `variant` support to `SelectField`

package-lock.json, package.json
Reactist is currently a blocker to the undergoing efforts to enable React v18 in Todoist (https://github.com/Doist/todoist-web/issues/4910). The reason is that one of its dependencies, Ariakit, throws at times a `Cannot call an event handler while rendering.` error from its own internal `useEvent` function, and it shouldn't. While visually it's not a breaking issue, several unit tests fail.
This problem has been fixed in Ariakit a while ago (https://github.com/ariakit/ariakit/pull/1481), but we froze Ariakit's version because newer versions brought breaking changes (https://github.com/Doist/reactist/issues/688). The good news is that the fix is present in a version (`2.0.0-next.30`) that was deployed just before the one that's problematic(`2.0.0-next.32`).
For peace of mind, you can run …
=> chore: Update ariakit dependency to 2.0.0-next.30

CHANGELOG.md, src/new-components/badge/badge.module.css, src/new-components/badge/badge.stories.mdx, src/new-components/badge/badge.tsx
While preparing for [upcoming work](https://twist.com/a/1585/ch/628546/t/4031093/), I noticed that we're still using in Todoist an in-app badge component in some cases, alongside cases that are using the newer shared `Badge` component from Reactist.
As I prepared to unify all `Badge` uses in Todoist with the one from Reactist, I also realized that this one needs some improvements (most prominently, making it render as an inline element).
Other change: this removes the `text-transform: uppercase` style. According to most of our references to badges in design mockups, we're not expecting our badges to be all uppercase anymore.
-   [x] Executed `npm run validate` and made sure no errors / warnings were …
=> feat: Badge component improvements

.github/workflows/chromatic.yml
When working on https://github.com/Doist/reactist/pull/757, I noticed en error in the ["Publish to Chromatic" build](https://github.com/Doist/reactist/actions/runs/4224987339/jobs/7336654969):
```
Error: error:0308010C:digital envelope routines::unsupported
```
Based on ["the internet"](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported), it seems like this is due to fact that that build is running on Node v18, even though we're not (yet) intentionally supporting it in Reactist.
It actually started failing even before this PR, when I merged [my previous PR](https://github.com/Doist/reactist/pull/755). See this build: https://github.com/Doist/reactist/actions/runs/4224761740/jobs/7336138735
The best solution here seems to be to …
=> chore: Explicitely enforce Chromatic build node version

.github/workflows/publish.yml
Adds the `--provenance` flag to npm publish. For more details on this, see https://github.blog/2023-04-19-introducing-npm-package-provenance/
=> chore: Adds provenance flag to npm publish

package-lock.json, package.json, src/components/time/time.test.tsx
Fixes a flaky test caused by the time proceeding when asserting against time-specific output:
No release needed
=> test: Fix flaky Time component test by freezing clock

CHANGELOG.md, src/text-field/text-field.module.css, src/text-field/text-field.stories.tsx, src/text-field/text-field.tsx
While attempting to look into adding a new feature to the `TextField`[^1], I noticed a couple of issues with the text field `startIcon`:
1. The "click to focus" functionality was still not entirely accurate if one managed to click on the thin padding around the icon. This PR fixes it by capturing the click event on the input element wrapper that covers the entire area inside the borders.
2. The `startIcon` feature was tailored only for the default text field variant. When the text field was set in bordered mode, the icon placement does not look good.
[^1]: The new feature I'm looking into is related to enabling the text field to also have a slot on the right side, similar to the one for `startIcon`. However, the slot in question is for more than just icons. It's about enabling the text …
=> fix: Fixes to the startIcon feature on TextField

CHANGELOG.md, src/text-area/text-area.stories.tsx, src/text-area/text-area.tsx
=> fix: Ensure TextArea autoExpand is acknowledged on its initial value

.github/workflows/publish.yml
This PR fixes npm package provenance when publishing to npmjs, it was missing an important permission for the whole thing to work (I'm assuming based on the documentation since the only way to test this is to publish a new version, which I'm not going to force).
=> build: Fix npm package provenance

.github/workflows/publish.yml
Forgot to add `--provenance` when publishing to GitHub Packages on the [previous PR](https://github.com/Doist/reactist/pull/774). This one fixes that.
=> build: Fix npm package provenance (GitHub Packages)

CHANGELOG.md, src/text-field/text-field.stories.tsx, src/tooltip/tooltip.tsx
The design team recently suggested that they are considering using tooltips to convey that a field has an invalid value. Normally we'd use the `message` prop, but in the case they're looking into, a tooltip would be convenient.
When exploring if that would work (given that it sounds unconventional to have a tooltip attached to a text field) it was all mostly good. For instance, the tooltip is correctly associated as the accessible description of the field. However, there was a problem with the field loosing focus as soon as I typed the character that made the tooltip appears due to the value being invalid.
When investigating why, I found that it was caused by the tooltip anchor element being re-created (re-mounted a new instance of the component, in React lingo). But we really wanted the …
=> fix: Tooltip no longer re-created anchor when tooltip content changes

CHANGELOG.md, package-lock.json, package.json, src/prose/prose-example.ts, src/prose/prose.module.css
This will update the `Prose` component to apply link styles to inline code that are wrapped in a link. 
This should be updated in conjunction with https://github.com/Doist/typist/pull/309.
|Before|After|
|-|-|
|![image](https://github.com/Doist/reactist/assets/8531248/b2e4d708-1ceb-49bc-ab4a-1d0e6275e0d9)|![image](https://github.com/Doist/reactist/assets/8531248/caafeccd-a7db-4b79-8859-f5b07325237e)|
- …
=> feat: Use link colors when inline code is wrapped in links

CHANGELOG.md, src/menu/menu.less, src/menu/menu.stories.mdx, src/menu/menu.test.tsx, src/menu/menu.tsx
This PR enhances the `MenuItem` component to have props targeted at generating a more structured content inside it, rather than leaving it to the consumer of the component to build the menu item's content by using `children`.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
```jsx
<MenuItem>
<CoolIcon />
Click me to learn more…
</MenuItem>
```
</td>
<td>
```jsx
<MenuItem
icon={<CoolIcon />}
label="Click me to learn more…"
/>
```
</td>
</tr>
</table>
The ability to use the component `children` instead of this new props is kept. It may prove useful in the future, so it is likely a feature we won't remove. It will give the freedom to consumers of the menu components to carve out custom menu items when they need it.
Still, this is a breaking change. The inner layout of a menu item …
=> feat: Structured menu items

CHANGELOG.md, src/menu/index.ts, src/menu/menu.module.css, src/menu/menu.stories.mdx, src/menu/menu.tsx, src/styles/design-tokens.css
This brings in from Todoist the CSS styles we use for menus in Todoist and Twist.
Up until now, we've had the menus in Reactist styles in more basic ways, and dealt with the style changes as CSS overrides in the app code. This PR now makes Reactist provide the menu styling, as Reactist does for all its other components.
Additionally, this introduces two new menu components: `SubMenuItem` and `SubMenuList`. This was necessary for a few reasons:
1. These had specific styling needs that could not be addressed in the way we used to do sub-menus. The app was dealing with this in an ad-hoc way, but to achieve the library providing it, we needed the dedicated components.
2. In the specific case of `SubMenuItem`, we needed it because we needed a component that acted as a sub-menu button, but with …
=> feat: New menu styles

src/menu/menu.module.css, src/menu/menu.stories.mdx, src/menu/menu.tsx
Introduces menu item component to represent groups of menu items shown as icon-only items, like the ones in the following screenshot:
In the process, a couple of other adjacent improvements are included:
- Added the ability to include an info icon element on the side of menu group labels.
- Brought the menu group label styles to be the same expected in our apps (semibold text in primary text color, as opposed to the regular weight secondary color text that we used to have).
Similar to #792, I'll give you the test plan in a Todoist sister PR.
You are also encouraged to check things out here in Reactist via the `IconMenuItem Story` in storybooks.
-   [ ] Executed `npm run validate` and made sure no errors …
=> feat: Icon-only menu items, plus accessible menu group help links

CHANGELOG.md, package-lock.json, package.json, stories/components/Dropdown.stories.tsx, stories/components/Input.stories.tsx, stories/components/Select.stories.tsx
While browsing a couple of Reactist storybook stories, I've noticed that there are some broken links that don't include the path "reactist":
https://github.com/Doist/reactist/assets/1509326/26b1d8cf-3c44-41c7-97aa-b26bcb4fa96e
This PR should fix those links so that do include the correct path and therefore lead the viewer to the right place. 
-   [ ] Reviewed and approved Chromatic visual regression …
=> chore: Fix links to Reactist components in storybook stories

CHANGELOG.md, package-lock.json, package.json, stories/components/Dropdown.stories.tsx, stories/components/Input.stories.tsx, stories/components/Select.stories.tsx
Follow-up to https://github.com/Doist/reactist/pull/794 where I tried to fix a couple of broken links in our storybook stories.
> While browsing a couple of Reactist storybook stories, I've noticed that there are some broken links that don't include the path "reactist":
> 
> https://github.com/Doist/reactist/assets/1509326/26b1d8cf-3c44-41c7-97aa-b26bcb4fa96e
It turns out I didn't actually fix anything at all as the links are still missing the appropriate `/reactist` path which it seems not to be included in `window.location.origin` 😅
In this PR, I initially tried to address this by concatenating `window.location.origin` with `window.location.pathname` to (hopefully) get the correct Reactist URL path. However, that doesn't work either, because `pathname` will include `/iframe.html` as …
=> chore: Fix links to Reactist components in storybook stories using LinkTo

CHANGELOG.md, package-lock.json, package.json, src/text-area/text-area.module.css
Closes #776 
`overflow-wrap: anywhere` is added to stop the horizontal expansion of `TextArea` with `autoExpand={true}`.
-   [x] Executed `npm run validate` and made sure no errors/warnings were shown
It's a bug fix.
=> fix horizontal expansion of textarea with autoexpand={true}

CHANGELOG.md, package-lock.json, package.json, src/toast/toast.test.tsx, src/toast/use-toasts.tsx
Allow to provide a custom classname for toasts container.
This is a new feature, so a minor version update.
=> feat: add an option for a custom className for toasts container

.github/workflows/chromatic.yml, .github/workflows/deploy-storybook.yml, .github/workflows/publish.yml, .github/workflows/pull_request.yml
This PR updates the actions to versions that no longer rely on NodeJS 16, which has reached its end of life. By upgrading the actions, we ensure compatibility with the latest NodeJS 20 runtime.
For https://github.com/Doist/infrastructure-backlog/issues/628
=> chore: Update actions to support NodeJS 20

.github/workflows/chromatic.yml, CHANGELOG.md, package-lock.json, package.json, src/alert/alert.module.css, src/alert/alert.tsx, src/base-field/base-field.module.css, src/icons/alert-icon.tsx, src/password-field/password-field.stories.mdx, src/select-field/select-field.module.css, src/select-field/select-field.stories.mdx, src/styles/design-tokens.css, src/text-area/text-area.module.css, src/text-area/text-area.stories.mdx, src/text-field/text-field.module.css, src/text-field/text-field.stories.mdx
This changes the alert component's icons and default colours.
[Figma ref](https://www.figma.com/file/LYlWNzvhMDh907l07mPPQk/Product-Library---Web?type=design&node-id=8321-272616&mode=dev)
|Before|After|
|-|-|
|<img width="1018" alt="image" src="https://github.com/Doist/reactist/assets/8531248/2073a317-f13e-4993-8b75-fd7de0da7cc9">|<img width="855" alt="image" src="https://github.com/Doist/reactist/assets/8531248/7d5b72ec-16ef-43ac-a57b-06c93ebdcac6">|
-   [x] Bumped version in `package.json` and `package-lock.json` (`npm --no-git-tag-version version <major|minor|patch>`) …
=> feat: Update `<Alert>` component's design

CHANGELOG.md, package-lock.json, package.json
Adds support for Node v21.
Eventually it would be a good idea to remove support for legacy versions, like v16, but not doing that in this PR.
Requires a minor version bump.
=> chore: add support for Node v21

CHANGELOG.md, package-lock.json, package.json, src/badge/badge.module.css
Text inside a `Badge` should never wrap into multiple lines.
-   [ ] Added tests for bugs / new features (N/A)
-   [ ] Updated docs (storybooks, readme) (N/A)
New patch release.
=> fix: Prevent badge text from wrapping

CHANGELOG.md, package-lock.json, package.json, src/prose/prose.module.css
Removes the `vertical-align: text-top` style from inline code elements inside a `Prose` component.
The style `vertical-align` top is not needed. It causes an almost imperceptible misalignment in most browsers:
<details><summary>Screen recording</summary>
<p>
</p>
</details> 
But what's worse, in some situation (e.g. a certain Firefox version in Linux, or perhaps any Firefox in Linux), it does this, which is much more extreme:
<details><summary>Screenshot</summary>
<p>
</p>
</details> 
-   [ ] Added tests for bugs / new features (N/A)
-   [ ] Updated docs (storybooks, readme) (N/A)
-   [x] Bumped version in `package.json` and `package-lock.json` (`npm …
=> fix: Vertical alignment of inline code inside a `Prose` component

.storybook/preview-head.html, CHANGELOG.md, package-lock.json, package.json, src/box/box.module.css, src/components/keyboard-shortcut/keyboard-shortcut.less, src/prose/prose.module.css, src/styles/design-tokens.css
Adds a new design token variable (i.e. `--reactist-font-family-monospace`) for monospace font families, uses it everywhere for monospace elements, and updates the font family based on [this proposal](https://github.com/Doist/Issues/issues/8715#issuecomment-1895536756) approved by Julia H.
Minor release (new design token)
=> feat: Add `--reactist-font-family-monospace` with updated font family

CHANGELOG.md, package-lock.json, package.json, src/checkbox-field/checkbox-field.tsx, src/checkbox-field/use-fork-ref.ts, src/components/time/time.test.tsx, src/menu/menu.test.tsx, src/menu/menu.tsx, src/modal/modal.tsx, src/tabs/tabs.test.tsx, src/tabs/tabs.tsx, src/toast/use-toasts.tsx, src/tooltip/tooltip.test.tsx, src/tooltip/tooltip.tsx, src/utils/test-helpers.tsx
Upgrades to the latest Ariakit. Ariakit underwent a relatively major API change, a breaking change. However, given how we encapsulate their API within ours, I suspect that it is not a breaking change for us (to be determined).
We're releasing this as a beta version, so …
=> chore: Upgrade to @ariakit/react v0.3.14

CHANGELOG.md, package-lock.json, package.json, src/heading/heading.module.css, src/heading/heading.stories.tsx, src/heading/heading.test.tsx, src/heading/heading.tsx
We are seeing increased usage of 600 font-weight for headers (named `SF/Subheader 1, Semibold`. in Figma), so this exposes it as `medium` from the Header component
Minor
=> feat: Add 'medium' weight to Heading

CHANGELOG.md, package-lock.json, package.json, src/heading/heading.module.css, src/heading/heading.stories.tsx, src/heading/heading.test.tsx, src/heading/heading.tsx
Ensure the newest changes on `main` are available on `next` as well.
=> chore: Release 23.2.0 in 24.1.0-beta

CHANGELOG.md, package-lock.json, package.json, src/menu/menu.tsx, src/tooltip/tooltip.tsx
The changes here fix two issues we detected while attempting to upgrade to this version of Reactist and the new Ariakit in todoist-web:
1. 🟠 Opening the settings via keyboard while a menu is expanded, keeps the menu on top of the settings modal (https://share.cleanshot.com/SjvnsDLz)
<details><summary>Screen recording</summary><p>
https://github.com/Doist/reactist/assets/15199/632573ea-ea75-444b-87db-b0952e70220a
</p></details>
2. 🟠 Clicking with the mouse outside a tooltip to dismiss it and then hovering buttons will keep the tooltips rendered indefinitely (https://share.cleanshot.com/Y4mt2xWT)
<details><summary>Screen recording</summary><p>
https://github.com/Doist/reactist/assets/15199/dbaf4897-07ee-4cd3-89fb-48880f96a480
</p></details>
-   [x] Executed `npm run validate` and made sure …
=> fix: More ariakit upgrade fixes

CHANGELOG.md, package-lock.json, package.json, src/modal/modal.module.css
Ensure the newest changes on `main` are available on `next` as well.
=> chore: Release 23.2.1 in 24.1.4-beta

CHANGELOG.md, package-lock.json, package.json, src/modal/modal.module.css
This reverts https://github.com/Doist/reactist/pull/821 because it turns out that this is not something that we want to do.
Patch
=> revert: Modal alignment to middle at breakpoint adjustment

package-lock.json
A follow-up to https://github.com/Doist/reactist/pull/824 to fix the version number in the `package-lock.json` file.
=> chore: Fix version number in `package-lock.json` file

package-lock.json, package.json
I accidentally forgot to bump up the version to v23.3.0 in https://github.com/Doist/reactist/pull/826. This PR does that so we can release.
Minor
=> chore: Bump up version to v23.3.0

CHANGELOG.md, package-lock.json, package.json, src/badge/badge.module.css, src/badge/badge.stories.mdx, src/badge/badge.test.tsx, src/badge/badge.tsx
Brings in the latest changes from main into v24.2.0-beta.
* feat: Add 'medium' weight to Heading
* Update changelog
* Bump version
=> chore: Bring latest from main as v24.2.0-beta

CHANGELOG.md, package-lock.json, package.json, src/tabs/tabs.test.tsx, src/tabs/tabs.tsx
In #829 I made the mistake of not passing on the `onClick` handler to the underlying Ariakit `Tab` component.
v25.0.0-beta.2
=> fix: fix tab click

CHANGELOG.md, package-lock.json, package.json, src/modal/modal-stories-components.tsx, src/modal/modal.module.css, src/modal/modal.tsx
This PR adds the `xsmall` size to the `Modal` component, and changes the `small` value from `450px` to `480px` so that the new Information/Confirmation modals can be stacked on top of other modals like this:
Minor
=> feat: Add `xsmall` size to the `Modal` component

CHANGELOG.md, src/tooltip/tooltip.stories.tsx, src/tooltip/tooltip.tsx
https://github.com/Doist/Issues/issues/15139
This exposes the show and hide timeout options for the Tooltip component to allow for customization.
Minor
=> feat: Expose `showTimeout` and `hideTimeout` props for `Tooltip`

CHANGELOG.md, src/alert/alert.module.css, src/alert/alert.tsx
This fixes the alignment for icons in the `<Alert>` component, spotted by @pauloslund over at https://github.com/Doist/todoist-web/pull/8223#pullrequestreview-1706995679
Patch
=> fix: Better alignment for Alert icons

CHANGELOG.md, package-lock.json, package.json, src/menu/menu.stories.mdx, src/menu/menu.tsx
This makes the `MenuList` component render with `flip="bottom"` as a default when it's a part of a submenu.
This will replace the fixes done in https://github.com/Doist/todoist-web/pull/11835
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/fbd41fc2-588b-4e54-a6c0-d661d1a12928)|![image](https://github.com/user-attachments/assets/340177fb-8ce6-41a1-aee2-b4ee3728c79d)|
-   [x] …
=> fix: Render submenus at the bottom when there isn't enough space

CHANGELOG.md, package-lock.json, package.json, src/tooltip/tooltip.stories.tsx, src/tooltip/tooltip.tsx
Back in https://github.com/Doist/reactist/pull/845, I exposed Ariakit's `showTimeout` and `hideTimeout` props to `Tooltip` to allow for customization, but it wasn't until I went to integrate it did I realize my mistake - we don't want to have to set this on every single tooltip instance 🥲 So we are adding a provider in order to be able to define these values just once in the app.
Ref: https://github.com/Doist/Issues/issues/15139
-   [x] Bumped version in `package.json` and `package-lock.json` (`npm --no-git-tag-version version <major|minor|patch>`) …
=> feat: Add TooltipContext to set global timeout values

CHANGELOG.md, package-lock.json, package.json, src/tooltip/index.ts, src/tooltip/tooltip.stories.tsx, src/tooltip/tooltip.tsx
Follow up to #845 and #846
Hopefully, third time's the charm 🥲😥😅 I did not realize these barrel files were crucial to what's exposed from the library until I tried to bring it in-app. Figured I'd take this opportunity to provide a better interface as a component so consumers don't need to memorize the values.
Patch
=> fix: Export TooltipProvider as a component

CHANGELOG.md, src/notice/notice.module.css, src/notice/notice.tsx
This fixes the vertical alignment for icons in the `Notice` component (https://github.com/Doist/Issues/issues/15416).
Patch
=> fix: Better icon alignment for the `Notice` component

src/notice/notice.module.css, src/notice/notice.tsx
Follow-up to https://github.com/Doist/reactist/pull/848, so that the markup and selectors are more consistent with the `Alert` component.
n/a
=> chore: Review markup and selectors for the `Notice` component

CHANGELOG.md, package-lock.json, package.json, src/tabs/tabs.module.css
Part of https://github.com/Doist/Issues/issues/15556
Explicitly set the `line-height` of tabs to 21px per design. Otherwise, multi-line tabs (thank you, German) will look off.
patch
=> fix: Set Tab line-height to 21px

CHANGELOG.md, src/tabs/tabs.module.css, src/tabs/tabs.stories.mdx
Following up from https://github.com/Doist/reactist/pull/851, this adds top/bottom paddings to the tabs so that they render at the same height as before the line-height change. Paddings are used over min-height so that they remain consistent even if multiple lines of text are rendered in the tabs.
|Before|After|
|-|-|
|<img width="214" alt="image" src="https://github.com/user-attachments/assets/a0ac82fd-bbc0-407e-a9d8-549dae7b244a" />|<img width="211" alt="image" src="https://github.com/user-attachments/assets/56f8dbaa-c7bd-470a-944e-a914ef0ce848" />|
|<img width="225" alt="image" src="https://github.com/user-attachments/assets/280bc014-a37b-4ef1-b82b-888e05136bc7" />|<img width="231" alt="image" src="https://github.com/user-attachments/assets/1f43cc84-3912-432c-9b05-5fa990035a74" />|
- …
=> fix: Set correct height for tabs

CHANGELOG.md, package-lock.json, package.json, src/menu/menu.stories.mdx, src/menu/menu.tsx
In https://github.com/Doist/reactist/pull/844, submenus were set up to render on the bottom if there isn't enough space to the right. Visually this doesn't look quite correct when the menu is placed closer to the right side of the screen and that there's space on the left, so having the left side as the first fallback should be preferred.
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/80dadb1c-9cef-42be-a8b0-1c0f7770b50f)|![image](https://github.com/user-attachments/assets/e6810cfa-9b59-4112-bf03-dc2265cdab0e)|
-   [x] Bumped version in `package.json` …
=> fix: Prefer flipping submenu to left side over to the bottom

CHANGELOG.md, package-lock.json, package.json, src/base-field/base-field.tsx, src/text-field/text-field.stories.mdx, src/text-field/text-field.tsx
Document the `maxLength` property in the TextField component on arguments able and a new story.
- [Docs] Document the `maxLength` prop for the `TextField` component.
=> docs: document maxLength property in TextField component

CHANGELOG.md, package-lock.json, package.json, src/icons/banner-icon.module.css, src/icons/banner-icon.tsx
The `Banner` component system types icons had their colors hardcoded. In this PR we are changing that so that they can be customized through CSS variables. The default colors are the same as the ones previously harcoded.
Minor -> 27.1.0
=> style: allow customization of system 'Banner' icons through CSS variables

CHANGELOG.md, package-lock.json, package.json, src/text-link/text-link.module.css, src/text-link/text-link.stories.mdx, src/text-link/text-link.test.tsx
- Add Storybook documentation for the TextLink component
- Change default styling to use tertiary actionable colors and underline decoration
=> fix: create documentation for TextLink and adjust style

src/badge/badge.module.css, src/text-link/text-link.module.css, src/text-link/text-link.stories.mdx
Hover styles (text decoration and color) were only applied to the container element itself. This caused inconsistent behavior when the text link contained nested elements, as the hover styles wouldn't propagate to the children.
This PR uses `.container:hover > *` selector to target immediate children.
=> fix: ensure TextLink styles are applied to nested elements

CHANGELOG.md, package-lock.json, package.json
Prepare release bump from 27.2.0 to 27.2.1
- [Fix] ensure TextLink styles are applied to nested elements [#860](https://github.com/Doist/reactist/pull/860)
=> chore: bump version to 27.2.1

.github/dependabot.yml, .github/release-please-config.json, .github/workflows/release-please.yml, README.md
Change dependabot commit prefix to `build(deps)` and exclude `chore` from releases. We need one excluded type for various changes, but mostly for release commits that are something like `chore(release)`, if we consider `chore` in releases and changelog, new commit releases will also be included in the upcoming release.
=> ci: change dependabot commit prefix

.github/workflows/deploy-storybook.yml
With the introduction of release PRs workflow (https://github.com/Doist/reactist/pull/863), we only want to deploy latest changes to Storybook when publishing new release.
=> ci: deploy storybook only when publishing package

src/base-field/base-field.tsx
As per new specification ([ref](https://twist.com/a/1585/ch/765851/t/6664583/c/93631846)), this PR changes character count threshold to determine when to set error tone to text field component.
**Before:**
**After:**
=> fix(TextField): adjust character count threshold to zero

src/base-field/base-field.tsx, src/select-field/select-field.tsx, src/text-field/text-field.module.css, src/text-field/text-field.stories.mdx, src/text-field/text-field.test.tsx, src/text-field/text-field.tsx
This PR introduces a new feature to customize the character count position in text fields. Major changes include:
- Added a new `characterCountPosition` prop to `BaseField` component with three options (two of them new):
- `'below'` (default) - shows the counter below the field
- `'inline'` - displays the counter inline with the field content
- `'hidden'` - hides the character counter completely
- Updated `TextField` component to support the new character count positioning feature
- Added new stories and examples in the documentation
- Added test coverage for the new feature
- Twist thread: https://twist.com/a/1585/ch/765851/t/6664583/
=> feat(TextField): add support for customizable character count position

.github/workflows/deploy-storybook.yml
Bump `upload-pages-artifact` version from v1 to v4 as per deprecation notice:
- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> ci: update Storybook deployment action to v4

.github/workflows/publish.yml, .github/workflows/release-please.yml
When using release-please with GITHUB_TOKEN, the tag creation doesn't trigger subsequent workflows due to GitHub's security limitations. This PR implements a workaround by:
1. Adding `workflow_dispatch` trigger to the `publish` workflow
2. Extending release-please workflow to programmatically trigger dependent workflows (`publish` and `deploy-storybook`) after a successful release
This makes use of Github's script action: https://github.com/actions/github-script
=> ci: enhance release workflow with automatic deployment triggers

.github/workflows/release-please.yml
Closes #...
Add `release-please` workflow permission to trigger other workflows ([ref](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token)). Also, remove debug logs
=> ci: add permissions to dispatch workflows in release-please

.github/workflows/deploy-storybook.yml
Closes #...
After bumping `upload-pages-artifact` to v3 (https://github.com/Doist/reactist/pull/885), we need to bump also the deploy action.
Also added read permissions to actions as it's required: https://github.com/actions/deploy-pages/releases/tag/v4.0.0
> This version requires the permission actions: read in the workflows which use it.
=> ci: bump deploy-pages action to v4

src/text-link/text-link.module.css, src/text-link/text-link.stories.mdx, src/text-link/text-link.test.tsx, src/text-link/text-link.tsx
- Introduce color prop with 'default' and 'inherit' variants
- Add underline prop to control text-decoration
- Extend stories and tests to cover new styling options
=> feat(TextLink): Add color and underline styling options

src/tabs/tabs.module.css, src/tabs/tabs.stories.mdx, src/tabs/tabs.tsx
This PR adds support for the following customization settings for the `Tabs` component:
- CSS variables for hover and disabled states for the `Tab` component
- `--reactist-tab-themed-hover` / `--reactist-tab-neutral-hover`
- `--reactist-tab-themed-disabled` / `--reactist-tab-themed-disabled`
- A tab can be individually disabled with the `disabled` prop
- CSS variable for a box shadow for the selected tab
- `--reactist-tab-neutral-shadow` / `--reactist-tab-themed-shadow`
- Full width for the `TabList` component
- The `width` prop can be `full` or `maxContent` (default)
- Tab alignment for the `TabList` component
- The `align` prop can be `start` (default), `center`, or `end`
- CSS variable for a transition for the selected tab
- `--reactist-tab-selected-transition`
- …
=> feat(Tabs)!: Add support for additional customization settings

scripts/jestSetup.ts, src/tabs/tabs.tsx
This PR replaces our viewport‐only resize listener with a `ResizeObserver` on the tabs container itself, ensuring the selected tab is always correctly positioned whenever its parent’s width changes. In particular, it fixes an edge case where removing an inline element (for example, a status badge or "unread" count) from a tab causes the container to shrink without firing a window `resize` event, leaving the selected tab indicator out of sync.
**What’s changed:**
- **Replace** the `window.addEventListener('resize', …)` logic for updating the selected tab with a `ResizeObserver` attached to the tabs list container.
- **On resize** of the container or **on manual tab change**, run the same recalculation & repositioning logic for the active tab.
This makes the tabs component resilient to any …
=> fix(Tabs): Add resize observer for dynamic tab selection adjustments

src/text-area/text-area.stories.mdx, src/text-area/text-area.tsx
Fixes #911 
The main issue is that our current auto-expand implementation is more suitable for when the component is uncontrolled. When the component is controlled, it is better to use the `value` changes as the signal to run the effect.
This PR now changes the auto-expand to set up two different `useEffect` calls:
1. one that runs only when the component is uncontrolled (it uses the `oninput` event to update the auto-expand size)
2. one that runs only when the component is controlled (it has the `value` as dependency in the effect, to update the auto-expand size)
=> fix: fix text area auto-expand when controlled

src/toast/static-toast.tsx, src/toast/toast.stories.tsx, src/toast/toast.test.tsx, src/toast/use-toasts.tsx
Adds a new prop to the `useToasts` hook: `showStickyToast`. This works exactly as seen in Storybook when checking the sticky toast checkbox [here](https://doist.github.io/reactist/?path=/docs/design-system-toast--notification-toasts-story). Except that state is managed locally in the story. 
We're exposing via the hook to give consumers a chance to choose whether the action calls `onDismiss` (which aside from closing the toast, would also call any logic consumers are passing into `onDismiss`, which may be undesirable).
=> feat: Expose closeToast in useToasts hook action object

src/toast/use-toasts.tsx
This updates the `Toast` component so that its auto dismiss effect is compatible with new `<StrictMode>` behaviours in dev mode. As we can no longer assume effects are just run once, this removes the `timeoutRunning` state, reducing the reliance on the `setupAutoDismiss` effect and instead allow `startTimeout` to set the timeout directly.
* Run storybook and navigate to http://localhost:6006/?path=/docs/design-system-toast--notification-toasts-story. 
https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development
=> fix: Toasts can be auto-dismissed when concurrent mode is enabled

src/box/box.module.css
This PR removes the default `font-size` from the `Box` component to avoid unintentionally overriding the font-size of its children. Components like `Stack`, which use `Box` internally, can inherit typography from their parent. Forcing a specific font-size in `Box` causes issues when nesting text elements, leading to inconsistent styles and the need for manual overrides like `font-size: inherit`. Removing this makes `Box` a more flexible layout utility and avoids unnecessary overrides.
- https://twist.com/a/1585/ch/190200/t/7035042/
=> fix(Box): Inherit `font-size` to prevent unintended typography overrides

src/modal/modal.test.tsx, src/modal/modal.tsx
The current `Modal` family of components uses the `Divider` component for the header and footer dividers (if specified with `withDivider`), and the weight of those divider usages is not specified - defaulting to the `tertiary` weight - without the ability to customize the weight for those dividers. However, on Todoist we want these dividers to be `primary`, and to prevent breaking changes, and `dividers` prop was added to the main `Modal` component that consumers can use to pick which divider weight they want to use for the header and footer dividers.
- https://github.com/Doist/todoist-web/pull/13829#discussion_r2157332877
=> feat: Add `dividers` prop to `Modal` to customize the weight for all dividers

src/base-field/base-field.module.css, src/select-field/select-field.module.css, src/styles/design-tokens.css, src/text-area/text-area.module.css, src/text-field/text-field.module.css
This PR updates the `BaseField` component styling to match the form field spec:
- https://www.figma.com/design/5gTX7MuUxhCIvL6WK87JVA/24Q3-Foundation?node-id=1947-125676&m=dev
=> fix: Update `BaseField` styling to match the form field spec

src/banner/banner.module.css, src/banner/banner.stories.mdx
For the purpose [of adding a QR code banner](https://app.todoist.com/app/task/web-triggered-sidebar-card-with-qr-code-6cWMwvjqRrf3WcM7) to the app, we'd like the banner with the image to use the full width of its container. This is currently not possible, because the banners with images get automatically narrowed to the image's width.
This PR enables the user to choose if the banner with an image should be narrowed (default behaviour) or if it should stretch to the full width.
This solution leverages CSS vars to set the banner's min-width. 
- Required for https://app.todoist.com/app/task/web-triggered-sidebar-card-with-qr-code-6cWMwvjqRrf3WcM7
=> fix: Enable banner with an Image to use container full width (with CSS vars)

src/button/button.stories.mdx, src/button/button.tsx, src/spinner/spinner.tsx
This PR reduces the size of the loader icon that gets displayed inside a `<Button>` component, when the `loading` prop is true. More specifically, the loader size was `24px` prior to this PR. This PR changes it to `18px`.
- [Todoist task](https://app.todoist.com/app/task/web-add-appropriately-sized-loader-spinner-to-upload-photo-flow-6cpWVf4jmRRpqFW7)
- Requested [in Figma here](https://www.figma.com/design/z4zytHrQew1cySsuoVVckt?node-id=1884-226828&m=dev#1411492158)
- Discover the need for this fix while implementing https://github.com/Doist/todoist-web/pull/14237
- Enables https://github.com/Doist/todoist-web/pull/14639
<table>
<thead><tr><th>Before</th><th>After</th></tr></thead>
<tbody>
<tr><td>
https://github.com/user-attachments/assets/00f7b102-362e-44bf-8fa1-6f4887fa9e6a
</td><td> …
=> fix: Smaller loader in `<Button>` component

src/text-area/text-area.stories.mdx, src/text-area/text-area.test.tsx, src/text-area/text-area.tsx
When a controlled `TextArea` has the `autoExpand` prop omitted or set to false, it would still expand based on the content as the `setupAutoExpandWhenControlled` effect was missing a check for the prop.
|Before|After|
|-|-|
|<img width="442" height="269" alt="image" src="https://github.com/user-attachments/assets/5321a206-5ee3-4f6e-a011-60bd553aeb78" />|<img width="444" height="158" alt="image" src="https://github.com/user-attachments/assets/0f4c15cf-fce0-4a88-a37b-da5276a23e7d" />|
=> fix: Prevent a controlled TextArea from expanding when autoExpand is false
